In [ ]:
%pip install tensorflow

In [ ]:
%pip install scikit-learn

In [117]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
import numpy as np

from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler

In [118]:
X,y = make_regression(n_features=10,n_samples=10000,n_targets=1, 
                      noise=0.5, random_state=42)

In [119]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [120]:
scaler = StandardScaler()
X_train_norm = scaler.fit_transform(X_train)
X_test_norm = scaler.transform(X_test)

In [121]:
X_train_norm.shape

(8000, 10)

In [122]:
model = Sequential([
    Dense(64,activation='relu',input_shape = (10,)),
    Dense(32,activation='relu'),
    Dense(1)
])

c:\Users\Techer314\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [123]:
model.compile(optimizer='sgd',loss='mae',metrics=['mae','mse'])

In [124]:
history = model.fit(X_train_norm,y_train,epochs=6,verbose=1)

Epoch 1/6
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 128.0348 - mae: 128.0348 - mse: 25644.3574
Epoch 2/6
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.7730 - mae: 16.7730 - mse: 941.7202
Epoch 3/6
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3296 - mae: 6.3296 - mse: 66.7338
Epoch 4/6
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.5856 - mae: 5.5856 - mse: 53.9007
Epoch 5/6
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.4426 - mae: 5.4426 - mse: 51.9930
Epoch 6/6
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.1604 - mae: 5.1604 - mse: 47.5103


In [125]:
model.evaluate(X_test_norm,y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.6678 - mae: 4.6678 - mse: 32.0443


[4.686986446380615, 4.686986446380615, 32.44974136352539]

In [126]:
y_model = model.predict(X_test_norm)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [127]:
X_new = [[23,45,67,89,212,-3,45,4,5,9]]
X_new_norm = scaler.transform(X_new)
model.predict(X_new_norm)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[12679.633]], dtype=float32)

In [128]:
X_new_norm

array([[ 23.21735613,  44.78327505,  67.43154275,  89.15810363,
        211.23011064,  -2.98146195,  44.96209082,   3.97610279,
          4.87210328,   9.07570777]])

In [129]:
y_model.shape

(2000, 1)

In [130]:
y_test.shape

(2000,)

In [131]:
max(y_model.squeeze()-y_test)

np.float64(6.586897975570295)

In [132]:
max(y_model), max(y_test)

(array([494.87857], dtype=float32), np.float64(501.7405677180696))